create table conduct_drug (
	conduct_drug_id integer generated by default as identity primary key,
	conduct_id integer not null references conduct (conduct_id),
	iyakuhincode integer not null check (iyakuhincode > 0),
	amount decimal (6,2) not null check (amount >= 0)
);

create or replace function check_conduct_drug_fun() returns trigger as $$
	declare
		count integer;
	begin
		select count(*) into count from public.iyakuhin_master m, public.conduct c, public.visit v 
			where m.iyakuhincode = new.iyakuhincode
			and new.conduct_id = c.conduct_id
			and v.visit_id = c.visit_id 
			and m.valid_from <= date(v.visited_at)
			and (m.valid_upto is null or m.valid_upto >= date(v.visited_at));
		if count < 1 then
			raise exception 'cannot find iyakuhin master for conductdrug';
		end if;
		if count > 1 then
			raise exception 'found multiple iyakuhin masters for conduct drug';
		end if;
		return new;
	end;
$$ language plpgsql;

create trigger check_conduct_drug before insert or update on conduct_drug
	for each row execute procedure check_conduct_drug_fun();
