create table conduct_kizai (
	conduct_kizai_id integer generated by default as identity primary key,
	conduct_id integer not null references conduct (conduct_id),
	kizaicode integer not null check (kizaicode > 0),
	amount decimal(6,2) not null check (amount > 0)
);

create or replace function check_conduct_kizai_fun() returns trigger as $$
	declare
		count integer;
	begin
		select count(*) into count from kizai_master m, conduct c, visit v 
			where m.kizaicode = new.kizaicode
			and new.conduct_id = c.conduct_id
			and v.visit_id = c.visit_id 
			and m.valid_from <= date(v.visited_at)
			and (m.valid_upto is null or m.valid_upto >= date(v.visited_at));
		if count < 1 then
			raise exception 'cannot find kizai master for conduct kizai';
		end if;
		if count > 1 then
			raise exception 'found multiple kizai masters for conduct kizai';
		end if;
		return new;
	end;
$$ language plpgsql;

create trigger check_conduct_kizai before insert or update on conduct_kizai
	for each row execute procedure check_conduct_kizai_fun();
