create table disease (
	disease_id integer generated by default as identity primary key,
	patient_id integer not null references patient (patient_id),
	shoubyoumeicode integer not null check (shoubyoumeicode > 0),
	start_date date not null,
	end_date date,
	end_reason char(1) not null check (end_reason in ('N', 'C', 'S', 'D')),
	check (end_date is null or start_date <= end_date),
	check ((end_reason = 'N' and end_date is null) or 
		(end_reason <> 'N' and end_date is not null))
);

create or replace function check_disease_fun() returns trigger as $$
	declare
		count integer;
	begin
		select count(*) into count from byoumei_master m where m.shoubyoumeicode = new.shoubyoumeicode
			and m.valid_from <= new.start_date
			and (m.valid_upto is null or m.valid_upto >= new.start_date);
		if count < 1 then
			raise exception 'cannot find shoubyoumei code for disease';
		end if;
		if count > 1 then
			raise exception 'found multiple shoubyoumei codes for disease';
		end if;
		return new;
	end;
$$ language plpgsql;

create trigger check_disease before insert or update on disease
	for each row execute procedure check_disease_fun();