create table intraclinic_comment (
	comment_id integer generated by default as identity primary key,
	name varchar(255) not null,
	content varchar(255) not null,
	post_id integer not null references intraclinic_post (post_id),
	created_at date not null
);