create table kouhi (
	kouhi_id integer generated by default as identity primary key,
	patient_id integer not null references patient (patient_id),
	futansha integer not null check(futansha > 0),
	jukyuusha integer not null check(jukyuusha > 0),
	valid_from date not null,
	valid_upto date,
	check(valid_upto is null or (valid_from <= valid_upto))
);