create table koukikourei (
	koukikourei_id integer generated by default as identity primary key,
	patient_id integer not null references patient (patient_id),
	hokensha_bangou integer not null check(hokensha_bangou > 0),
	hihokensha_bangou integer not null check(hihokensha_bangou > 0),
	futan_wari smallint not null check(futan_wari in (0, 1, 2, 3)),
	valid_from date not null,
	valid_upto date,
	check(valid_upto is null or (valid_from <= valid_upto))
);