create table practice_log (
	practice_log_id integer generated by default as identity primary key,
	created_at timestamp not null,
	kind varchar(32) not null check(char_length(kind) > 0),
	body json not null
);