create table presc_example (
	presc_example_id integer generated by default as identity primary key,
	iyakuhincode integer not null,
	master_valid_from date not null,
	amount decimal(6,2) not null check (amount >= 0),
	usage varchar(255) not null,
	days smallint not null check (days >= 0),
	category smallint not null check (category in (0, 1, 2, 3)),
	comment varchar(255) not null,
	foreign key (iyakuhincode, master_valid_from) references
		iyakuhin_master (iyakuhincode, valid_from)
);

