create table roujin (
	roujin_id integer generated by default as identity primary key,
	patient_id integer references patient (patient_id),
	shichouson integer not null check(shichouson > 0),
	jukyuusha integer not null check(jukyuusha > 0),
	futan_wari smallint not null check(futan_wari in (0, 1, 2, 3)),
	valid_from date not null,
	valid_upto date,
	check(valid_upto is null or (valid_from <= valid_upto))
);