create table shinryou (
	shinryou_id integer generated by default as identity primary key,
	visit_id integer not null references visit (visit_id),
	shinryoucode integer not null check (shinryoucode > 0)
);

create or replace function check_shinryou_fun() returns trigger as $$
	declare
		count integer;
	begin
		select count(*) into count from shinryou_master m, visit v where m.shinryoucode = new.shinryoucode
			and v.visit_id = new.visit_id 
			and m.valid_from <= date(v.visited_at)
			and (m.valid_upto is null or m.valid_upto >= date(v.visited_at));
		if count < 1 then
			raise exception 'cannot find shinryou master for shinryou';
		end if;
		if count > 1 then
			raise exception 'found multiple shinryou masters for shinryou';
		end if;
		return new;
	end;
$$ language plpgsql;

create trigger check_shinryou before insert or update on shinryou
	for each row execute procedure check_shinryou_fun();

create index on shinryou (visit_id)+
