# -*- mode: ruby -*-
# vi: set ft=ruby :

mysql_root_password = ENV["MYCLINIC_MYSQL_ROOT_PASS"]
mysql_user = ENV["MYCLINIC_DB_USER"]
mysql_pass = ENV["MYCLINIC_DB_PASS"]
mock_data_folder = ENV["MYCLINIC_MOCK_DB_DATA_FOLDER"]
host_ip = ENV["MYCLINIC_MOCK_DB_HOST"] || "192.168.33.10"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: host_ip
  config.vm.synced_folder mock_data_folder, "/docker-entrypoint-initdb.d"
  config.vm.provision "docker" do |d|
  	d.run "mysql:5.7", 
  		args: "-v /docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d -e MYSQL_ROOT_PASSWORD=#{mysql_root_password} -e MYSQL_DATABASE=myclinic -e MYSQL_USER=#{mysql_user} -e MYSQL_PASSWORD=#{mysql_pass} -p 3306:3306 --name mock-mysql",
  		cmd: "--sql-mode='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'",
  		daemonize: true
  end
end
